service: lambda-test
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  # This is new
  apiGateway:
    binaryMediaTypes:
      - "*/*"
plugins:
  # - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  hello:
    handler: logic/handler.hello
    events:
      - http:
          path: user/create
          method: get
  generatePdf:
    handler: logic/index.generatePdf
#    layers:
#      - ${cf:executables-layer-${self:provider.stage}.HtmlToPdfLayerExport}
    events:
      - http:
          path: user/pdf
          method: get
          cors: true
          integration: lambda
